### ISSUE TITLE
Failures array in transition not being reset.

### ISSUE THREAD

**Issue by jmcnevin** [aasm/aasm#383] opened 2016-07-14 13:06 UTC
I'm wondering if anyone else has run into this issue with AASM 4.11 and Rspec.  I'm not sure if it relates to using `let` to define variables in specs.

As my specs run, I start to see failures in state transitions that worked in AASM 4.7, and the list of failures seems to compound with each spec run.  Example:

```
Event 'close' cannot transition from 'available'. Failed callback(s): [:ready_to_close?, :ready_to_close?].
Event 'close' cannot transition from 'available'. Failed callback(s): [:ready_to_close?, :ready_to_close?, :ready_to_close?, :ready_to_close?].
Event 'close' cannot transition from 'available'. Failed callback(s): [:ready_to_close?, :ready_to_close?, :ready_to_close?, :ready_to_close?, :ready_to_close?, :ready_to_close?].
Event 'close' cannot transition from 'available'. Failed callback(s): [:ready_to_close?, :ready_to_close?, :ready_to_close?, :ready_to_close?, :ready_to_close?, :ready_to_close?, :ready_to_close?, :ready_to_close?].
```

I have a feeling this is related to storing the failures in an instance variable on the transition object, and somehow that array of failures isn't being cleared properly between transition attempts.  Is there a way I should be configuring my test suite to prevent this?

**Comment by jmcnevin** [comment] 2016-07-14 16:56
Still having problems with this.

**Comment by jmcnevin** [comment] 2016-07-15 12:21
Attempted to fix this in my PR, but I'm still not following what's happening here:

```
x.may_close?
=> true
x.close!
=> *** AASM::InvalidTransition Exception: Event 'close' cannot transition from 'available'. Failed callback(s): [:ready_to_close?, :ready_to_close?].
x.may_close?
=> false
```

It appears some state is still being persisted between transition attempts/queries, but I'm having a tough time tracking down where this is happening.

**Comment by adamniedzielski** [comment] 2017-11-13 14:44
I managed to reproduce the bug against AASM 4.12.3 and narrow it down to a simple example. It's not specific to tests, we run into this bug in our production code for reporting exceptions from state transitions.

```ruby
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'activerecord', '5.1.4'
  gem 'sqlite3'
  gem 'aasm', '4.12.3'
end

require 'active_record'
require 'sqlite3'
require 'aasm'

puts "AASM: #{AASM::VERSION}"

ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')

ActiveRecord::Migration.create_table :documents do |t|
  t.string :aasm_state
end

class Document < ActiveRecord::Base
  include AASM

  aasm do
    state :initial, initial: true
    state :confirmed
    event :confirm do
      transitions from: :initial, to: :confirmed, guard: :foo?
      transitions from: :initial, to: :initial
    end
  end

  def foo?
    puts "GUARD"
    false
  end
end

doc_one = Document.new
doc_two = Document.new(aasm_state: "confirmed")

doc_one.confirm!

puts "first record transitions"

doc_two.confirm!

puts "this is never reached"
```

output:

```
AASM: 4.12.3
-- create_table(:documents)
   -> 0.0050s
GUARD
first record transitions
/Users/adam/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/aasm-4.12.3/lib/aasm/aasm.rb:199:in `aasm_failed': Event 'confirm' cannot transition from 'confirmed'. Failed callback(s): [:foo?]. (AASM::InvalidTransition)
	from /Users/adam/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/aasm-4.12.3/lib/aasm/aasm.rb:127:in `aasm_fire_event'
	from /Users/adam/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/aasm-4.12.3/lib/aasm/persistence/orm.rb:127:in `block in aasm_fire_event'
	from /Users/adam/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/aasm-4.12.3/lib/aasm/persistence/active_record_persistence.rb:86:in `block in aasm_transaction'
	from /Users/adam/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `block in transaction'
	from /Users/adam/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/transaction.rb:194:in `block in within_new_transaction'
	from /Users/adam/.rbenv/versions/2.4.2/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
	from /Users/adam/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/transaction.rb:191:in `within_new_transaction'
	from /Users/adam/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `transaction'
	from /Users/adam/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activerecord-5.1.4/lib/active_record/transactions.rb:210:in `transaction'
	from /Users/adam/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/aasm-4.12.3/lib/aasm/persistence/active_record_persistence.rb:84:in `aasm_transaction'
	from /Users/adam/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/aasm-4.12.3/lib/aasm/persistence/orm.rb:126:in `aasm_fire_event'
	from /Users/adam/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/aasm-4.12.3/lib/aasm/base.rb:129:in `block in event'
	from test.rb:47:in `<main>'
```

The important bit is "Event 'confirm' cannot transition from 'confirmed'. **Failed callback(s): [:foo?]**".

`doc_two` is in the state `confirmed` and there is no transition from this state. `doc_two` doesn't invoke `foo?` callback, but this callback is still reported as failed. That's because `doc_one` invoked this callback and the failure is somewhere incorrectly persisted as pointed out in the original bug report.

**Comment by gsmetal** [comment] 2018-07-09 16:24
Any chance this will be fixed? After achieving available events by `obj.aasm.events(permitted: true).map(&:name)` for each object of a list there is very confusing error message (with mix of different failures) on trying to do unpermitted action on one of objects.

**Comment by nedgar** [comment] 2018-09-05 23:49
I'm hitting this too in AASM 4.1.2.3. This bug is effectively a blocker for using guards at all.

It's due to the [`@failures` field in `Transition`](https://github.com/aasm/aasm/blob/v4.12.3/lib/aasm/core/transition.rb#L16) not being cleared at the start of `allowed?` and `execute`, and due to `Transition`s (and their parent `Event`s) being defined per state machine definition, so essentially global for a given transition declaration.
Looks like it's still in issue in [AASM 5 too](https://github.com/aasm/aasm/blob/aasm5/lib/aasm/core/transition.rb#L16).
In master, there's a new `Invoker` being used in [`invoke_callbacks_compatible_with_guard`](https://github.com/aasm/aasm/blob/master/lib/aasm/core/transition.rb#L74), but it's still passed the shared `@failures` array.

**Comment by anilmaurya** [comment] 2018-09-06 11:29
@nedgar Would you like to submit a PR for fixing this issue ?

**Comment by nedgar** [comment] 2018-09-06 22:57
@anilmaurya Yes. Would a PR against 4.x be acceptable?

**Comment by nedgar** [comment] 2018-09-06 23:04
One workaround I've found is:

- include this in the state machine definition:
```ruby
  before_all_events :aasm_clear_guard_failures
```
- alternatively, define the following below the state machine, as a private method:
```ruby
  def aasm_fire_event(state_machine_name, event_name, options, *args, &block)
    aasm_clear_guard_failures
    super
  end
```

Where `aasm_clear_guard_failures` can be defined in a superclass, e.g. `ApplicationRecord`:

```ruby
  # Workaround for https://github.com/aasm/aasm/issues/383#issuecomment-418917316
  # Clears any transition guard failures left from earlier checks.
  # For the default AASM, configure in the state machine declaration:
  #   before_all_events :aasm_clear_guard_failures
  # otherwise, the caller is responsible for looking up the AASM and passing it.
  def aasm_clear_guard_failures(aasm = nil)
    aasm ||= self.aasm
    aasm.events.each do |event|
      event.transitions.each do |transition|
        if transition.failures.any?
          Rails.logger.debug("Clearing #{transition.failures.size} earlier failures for transition in #{self.class.name}: #{transition.from} -> #{transition.to}")
          transition.failures.clear
        end
      end
    end
  end
```

**Comment by anilmaurya** [comment] 2018-09-07 08:37
@nedgar Thank you for helping out.
@adamniedzielski  Thank you for providing script to reproduce this bug.

I have released new version of aasm `5.0.1`, in which this issue is resolved.

Feel free to re-open issue for any queries.

**Closed by anilmaurya** 2018-09-07 08:37 UTC

**Comment by nedgar** [comment] 2018-09-07 14:06
Thank you, @anilmaurya. I think this is a fine fix for the short term, but it would be cleaner (and more thread-safe) to remove the `failures` list from `Transition` and instead populate a new list in the new `Invoker` (and have `may_fire?` check that). But the `Invoker` would have to be shared instead of recreated for the guard and unless passes.

**Comment by nedgar** [comment] 2018-09-07 14:07
Is 4.x under maintenance still? If so should your fix be backported? I'm not sure what the implications are for moving from 4.x to 5, but will check the release notes.

**Comment by nedgar** [comment] 2018-09-07 14:11
Hm, the README.md only discusses migrating from v3 to v4, not v4 to v5. The CHANGELOG.md doesn't either. It would be good to at least list any API changes, especially if there are breaking changes as suggested by the major version bump. Thanks.

**Comment by anilmaurya** [comment] 2018-09-07 14:15
Hi nick,

I agree with your points. If someone can raise a PR for this I will be
happy to merge it.

AASM 5 is backward compatible so you can upgrade to latest version.

Regards, Anil.
