### ISSUE TITLE
may_*? method `wrong number of arguments (given 1, expected 0)`

### ISSUE THREAD

**Issue by kntmrkm** [aasm/aasm#449] opened 2017-04-04 05:29 UTC
- AASM 4.12.0
- Rails 5.0.1

`may_contract?` method will be got below error.

```
ActionView::Template::Error (wrong number of arguments (given 1, expected 0)):
```

The error occur with below code.

```
    event :contract do
      transitions from: [:authorized], to: :contracted, guard: :can_contract?
    end

  ・・・・

  def can_contract?
    self.authorizer_id.present?
  end

```

But when rewite with below code. The error disappears.

```
    event :contract do
      transitions from: [:authorized], to: :contracted do
        guard do
          self.can_contract?
        end
      end
    end
```

**Comment by klaustopher** [comment] 2017-04-10 16:14
I got the same issues, when executing my test suite (mostly `it { is_expected.not_to allow_transition_to(:some_state) }`).

Everything works fine with 4.11.x

**Comment by hirox** [comment] 2017-04-14 09:48
Hello. I have no idea to fix it, but I found the cause of the error.

With this commit, https://github.com/aasm/aasm/commit/c3b6454e8e9ca499e57aac4c74ec18bf9fa028b4#diff-6323dc24ff3a8a3e52b3b26d63e926cdR126 (#404, #406), `args.unshift(nil) if args.blank?` was added and `args` will be `[nil]` although there is no arguments.
This change causes validation error because `can_contract?` expects 0 arguments.

**Comment by klaustopher** [comment] 2017-04-26 07:46
It's very strange, that this issue has been open for 22 days and nobody who's involved in the project has even acknowledged that a bug was introduced that breaks behavior that is documented in the readme.

**Comment by anilmaurya** [comment] 2017-04-26 08:35
Hi @klaustopher , Thank you for keeping eye on this issue.

I am running of time for last few weeks. Any help is much appreciated.

A failing test will help in solving issues quicker.

**Comment by anilmaurya** [comment] 2017-04-29 21:18
Hi @kntmrkm @klaustopher ,

I added a spec to test this scenario for ActiveRecord.

https://github.com/aasm/aasm/blob/master/spec/unit/guard_spec.rb#L86

Specs are passing without failure, may be I missed something.

Let me know what do you think

**Comment by hirox** [comment] 2017-05-01 11:25
Hello @anilmaurya ,
I found it occurs when rspec-mocks is used.
rspec-mocks destroys arity (from 0 to -1) and `record.__send__(code, *args)` (args == [nil]) is called here ( https://github.com/aasm/aasm/blob/master/lib/aasm/core/transition.rb#L72 )

Here is a backtrace.
```
~/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rspec-mocks-3.5.0/lib/rspec/mocks/verifying_proxy.rb:162:in `block in validate_arguments!'
~/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rspec-mocks-3.5.0/lib/rspec/mocks/verifying_proxy.rb:186:in `with_signature'
~/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rspec-mocks-3.5.0/lib/rspec/mocks/verifying_proxy.rb:160:in `validate_arguments!'
~/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rspec-mocks-3.5.0/lib/rspec/mocks/verifying_proxy.rb:155:in `proxy_method_invoked'
~/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rspec-mocks-3.5.0/lib/rspec/mocks/method_double.rb:64:in `block (2 levels) in define_proxy_method'
~/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/aasm-4.12.0/lib/aasm/core/transition.rb:72:in `invoke_callbacks_compatible_with_guard'
~/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/aasm-4.12.0/lib/aasm/core/transition.rb:116:in `block in invoke_callbacks_compatible_with_guard'
~/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/aasm-4.12.0/lib/aasm/core/transition.rb:116:in `each'
~/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/aasm-4.12.0/lib/aasm/core/transition.rb:116:in `all?'
~/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/aasm-4.12.0/lib/aasm/core/transition.rb:116:in `invoke_callbacks_compatible_with_guard'
~/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/aasm-4.12.0/lib/aasm/core/transition.rb:116:in `block in invoke_callbacks_compatible_with_guard'
~/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/aasm-4.12.0/lib/aasm/core/transition.rb:116:in `each'
~/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/aasm-4.12.0/lib/aasm/core/transition.rb:116:in `all?'
~/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/aasm-4.12.0/lib/aasm/core/transition.rb:116:in `invoke_callbacks_compatible_with_guard'
~/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/aasm-4.12.0/lib/aasm/core/transition.rb:41:in `allowed?'
~/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/aasm-4.12.0/lib/aasm/core/event.rb:143:in `block in _fire'
~/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/aasm-4.12.0/lib/aasm/core/event.rb:140:in `each'
~/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/aasm-4.12.0/lib/aasm/core/event.rb:140:in `_fire'
~/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/aasm-4.12.0/lib/aasm/core/event.rb:44:in `may_fire?'
~/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/aasm-4.12.0/lib/aasm/instance_base.rb:102:in `may_fire_event?'
~/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/aasm-4.12.0/lib/aasm/base.rb:121:in `block in event'
~/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/aasm-4.12.0/lib/aasm/instance_base.rb:74:in `block in events'
~/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/aasm-4.12.0/lib/aasm/instance_base.rb:74:in `select!'
~/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/aasm-4.12.0/lib/aasm/instance_base.rb:74:in `events'
~/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/aasm-4.12.0/lib/aasm/instance_base.rb:38:in `states'
```

**Comment by anilmaurya** [comment] 2017-05-06 07:43
Thanks @hirox  for the pointer .

@kntmrkm , @klaustopher can you confirm that you are also facing this issue while using rspec-mocks ?

**Comment by klaustopher** [comment] 2017-05-11 12:23
I can confirm that we have `rspec-mocks` in our test suite. I have not tested if the code works in `development` where we are not including it.

**Comment by bessey** [comment] 2017-05-11 23:01
This is bizarre, I am encountering this issue in production, but I am _not_ encountering it in my dev environment, even though my `rspec` dependency is exclusively in the `:development` group in my Gemfile, so the two envs should be no different...

Here's the error we get in production (`#lead_returned` is an `:after` for one of our transitions)

![image](https://cloud.githubusercontent.com/assets/708200/25972526/2c3ff282-3655-11e7-9991-95c5c13ec7ad.png)

We are calling this particular transition with an argument, which according to the docs requires passning the end state as the first argument, however that is **not true**, its actually optional. I worked around the issue by replacing `lead.return(end_state, 123)` with `lead.return(123)`.

Hopefully this information is helpful to the next person...

**Comment by anilmaurya** [comment] 2017-05-18 18:05
Hi @bessey ,

I think your issue is not related to the this issue, Can you create separate issue with all details.

I would like to see **event** and **transition** definition for further investigation.

Thanks

**Comment by anilmaurya** [comment] 2017-05-18 18:43
Hi @hirox ,

Thank you for your help so far. Could you help little more ?

 Can you confirm rspec-mocks destroys arity only for 0 argument and maintains arity if arguments is present ?

If so then 
```
result = (record.__send__(:method, code.to_sym).arity > 0 ? record.__send__(code, *args)) : record.__send__(code)

```
will solve this issue.

**Comment by bessey** [comment] 2017-05-19 16:13
I'm not so sure it isn't related; it has to do with an exception relating
to arity, and it behaves differently in testing to in development. I also
use rspec.

If i find some free time soon i will put together a test case

**Comment by hirox** [comment] 2017-05-22 14:44
Hello @anilmaurya ,

I confirmed it solve the issue (I fixed syntax error)
```
result = (record.__send__(:method, code.to_sym).arity > 0 ? record.__send__(code, *args) : record.__send__(code))
```

**Comment by anilmaurya** [comment] 2017-05-22 14:58
Thank you @hirox , I really appreciate your help ♡ 🎖

**Comment by teohm** [comment] 2017-07-19 03:43
@anilmaurya Hi, can confirm if this bug fix is released?

**Comment by anilmaurya** [comment] 2017-07-25 14:07
@teohm This bug fix is released in `4.12.1`

**Closed by anilmaurya** 2017-07-25 14:07 UTC
Labels: bug

**Comment by hirox** [comment] 2017-07-25 17:39
Hello @anilmaurya ,
I found this fix https://github.com/aasm/aasm/commit/a6152fe3f38a7c5e5688ae36577f439dc23949e2 was canceled with this fix https://github.com/aasm/aasm/commit/d3c0e3e08bc28ad60adc17507b8b1ba90531dccb , so I think this issue is not fixed yet.

**Comment by teohm** [comment] 2017-07-26 00:57
I dig a bit more into the recent PRs. As mentioned earlier by @hirox, the breaking change was introduced into [core/event.rb:137](https://github.com/aasm/aasm/blame/v4.12.1/lib/aasm/core/event.rb#L137) when fixing https://github.com/aasm/aasm/issues/404.

imho, we should fix the root cause over there instead?

The line at [core/event.rb:137](https://github.com/aasm/aasm/blame/v4.12.1/lib/aasm/core/event.rb#L137) was intended to be triggered when guard method with single argument receives a nil value e.g. `record.can_change?(nil)`, but it's incorrectly triggered when guard method has no argument as well.

```
def _fire(obj, options={}, to_state=nil, *args)
  ...
  args.unshift(nil) if args.nil? || args.empty? # If single arg given which is nil, push it back to args
```

The `args.empty?` should be removed, because `*args` returns `[]` when guard method has no argument.

```
# correct
def _fire(obj, options={}, to_state=nil, *args)
  ...
  args.unshift(nil) if args.nil? # If single arg given which is nil, push it back to args
```

Does it make sense? @anilmaurya

**Comment by anilmaurya** [comment] 2017-07-26 05:54
@hirox are your test still failing on `4.12.1` ? https://github.com/aasm/aasm/commit/d3c0e3e08bc28ad60adc17507b8b1ba90531dccb is not cancelling https://github.com/aasm/aasm/commit/a6152fe3f38a7c5e5688ae36577f439dc23949e2 .
@teohm are you facing this issue on `4.12.1` release ?

**Comment by teohm** [comment] 2017-07-26 06:09
@anilmaurya Yes, our app fails after upgraded to 4.12.1.

The failure happens when guard method is a delegated method (using Rails's `delegate`), because the delegated method is always generated with a `*args` argument, example:

```ruby
class Foo < ActiveRecord::Base
  belongs_to :bar
  delegate :can_something?, to: :bar  
  # the line above generates a proxy method looks something like this:
  #   def can_somethings?(*args, &block)
  #     # forward msg to `bar`
  #   end

  aasm do ... end
end

class Bar
  def can_something?  # no argument
    true
  end
```

**Comment by anilmaurya** [comment] 2017-07-26 07:04
@teohm Looks like checking arity is not the best solution, Do you have any suggestion or work around ?

I think your issue is related to https://github.com/aasm/aasm/issues/416

**Comment by teohm** [comment] 2017-07-26 11:05
@anilmaurya ideally AASM should forward the **exact same** argument(s) provided by caller to the guard method, if there is no argument, AASM should trigger guard method without argument.

the `to_state` argument's default `nil` value in method`AASM::Core::Event#_fire(obj, options={}, to_state=nil, *args)` is causing ambiguity, there is no way for AASM to tell if caller provides argument or not.

What the default value of `to_state` argument is a symbol?  `AASM::Core::Event#_fire(obj, options={}, to_state=:none, *args)`. Do you think this will remove the ambiguity?

**Comment by anilmaurya** [comment] 2017-07-26 11:17
It make sense to use symbol over nil , Did you tried this solution ?

If it works and all specs passes then we are good to go with this solution.

**Comment by teohm** [comment] 2017-07-26 11:20
@anilmaurya Gimme some time to test it, will try to submit a PR later today or tomorrow. :)

**Comment by anilmaurya** [comment] 2017-07-26 11:26
@teohm Looking forward for PR, thank you for helping out ♡

**Comment by teohm** [comment] 2017-07-26 13:38
@anilmaurya I pushed a PR https://github.com/aasm/aasm/pull/484 , take a look 👀 ?
