### ISSUE TITLE
no_direct_assignment: true couldn't be turned off pragmatically

### ISSUE THREAD

**Issue by chitsaou** [aasm/aasm#636] opened 2019-06-24 08:34 UTC
**Describe the bug**

Using AASM with ActiveRecord, when `no_direct_assignment: true` is set on `aasm` class method call, it cannot be turned off by setting `Klass.aasm.state_machine.config.no_direct_assignment = false`, because the assignment method has been overridden.

**To Reproduce**

1. Consider the following code:
    ```rb
    require 'aasm'

    class Job < ActiveRecord::Base
      include AASM

      aasm no_direct_assignment: true do
        state :sleeping, initial: true
        state :running
      end
    end
    ```
2. Turn the 'no direct assignment' off using:
    ```rb
    Job.aasm.state_machine.config.no_direct_assignment = false
    ```
3. Try to assign state directly
    ```rb
    job = Job.new
    job.aasm_state = 'running'
    ```
4. The state did not change:
    ```rb
    job.aasm_state #=> 'sleeping'
    ```

**Expected behavior**

Expecting `job.aasm_state = 'running'` to change the state value to `'running'`.

**Screenshots**
N/A

**Additional context**

1. I was trying to turn the `no_direct_assignment` off in unit tests, so that I can jump to a particular state in the state machine.
2. I assume this behavior is caused by the fact that, the `#aasm_state=` method is overridden with a no-op method in `AASM::Base#initialize`, when `no_direct_assigment == true`. If you turn it off during runtime, it will be a no-op because the method returned without doing anything. See https://github.com/aasm/aasm/blob/v5.0.5/lib/aasm/base.rb#L58-L64
3. I am not sure if this is a bug or feature, but I spent 1 hour trying to figure out if I did something wrong (symbol vs string, or ActiveRecord-specific) until I looked into the code in AASM. Hope this helps someone even if AASM team decided not to change any behavior that this issue describes.

**Comment by ipranay** [comment] 2019-08-01 18:29
I think this was introduced in a recent version. Guessing this might be the cause: https://github.com/aasm/aasm/pull/627

**Comment by bobes** [comment] 2019-08-18 16:35
This commit removed `else super(state_name)` from the method:

https://github.com/aasm/aasm/commit/d185921d9035a0f3a564e978953d2d476bc5e750#diff-b8d4c2d34e62d1889f6296e352014c10

This means that setting `no_direct_assignment = false` programmatically doesn't raise exception but doesn't set the value either.

This change was introduced in v5.0.4 so if you need this feature, use v5.0.3.

**Comment by chitsaou** [comment] 2019-08-29 09:09
Thanks for all of your replies. If this is an intended behavior, it'd be great to raise an error in the runtime, so that it doesn't confuse developers 😃

**Comment by pacso** [comment] 2019-09-04 07:21
I have been using this in testing to allow objects to be created in a given state, without having to jump through state transitions from the initial state in the test setup.

What is the recommended replacement for using `Class.aasm.state_machine.config.no_direct_assignment` in my test setup now? Seems unnecessary to force people to jump through all of the state transitions to get to a particular state just for testing.

**Comment by anilmaurya** [comment] 2019-09-04 09:49
Published `5.0.6` with fix, Please try it @pacso

**Comment by anilmaurya** [comment] 2019-09-04 09:50
Hi @chitsaou , thank you for reporting this bug.
I just released `5.0.6` version with fix, can you verify it ?

**Comment by pacso** [comment] 2019-09-04 15:37
@anilmaurya - all my tests passing with version `5.0.6` 👍

**Comment by anilmaurya** [comment] 2019-09-04 16:46
Thanks @pacso for confirmation.
I am closing this issue. @chitsaou Please reopen it if its not fixed for you.

**Closed by anilmaurya** 2019-09-04 16:46 UTC

**Comment by chitsaou** [comment] 2019-09-05 10:44
Thanks @anilmaurya and sorry for late response. Really appreciate your help on this issue!

I am not currently working on a project that is using aasm, but I'll let my ex-team members know this change and check it out in the test code. Thanks again 🙇
